### ISSUE TITLE
Error raised after updating to 0.8.0: undefined method `logger' for MyApp::Application:Class

### ISSUE THREAD

**Issue by titusgahissy** [googleapis/google-api-ruby-client#183]
The trace goes back to that line:

```
/google/api_client/railtie.rb:13:in `block in <class:Railtie>
```
